version: "3.8"

services:
  microservice-01:
    image: doe-api
    restart: unless-stopped
    working_dir: /var/www
    build:
      args:
        user: usuario
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: api-service-doe
    volumes:
      - ./:/var/www
    networks:
      - api-service-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
    networks:
      - api-service-network

  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
    ports:
      - 3366:3306
    volumes:
      - ./.docker/mysql/db_data:/var/lib/mysql
    networks:
      - api-service-network

networks:
  api-service-network:
    driver: bridge